name: Create Release Workflow

on:
  push:
    branches:
      - main

jobs:
  all-checks:
    uses: ./.github/workflows/all-checks.yml
  build-and-publish:
    needs: [all-checks]
    uses: ./.github/workflows/rw-build-publish.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.10"
      changelog-file: "CHANGELOG.md"
