name: Build and Publish Reusable Workflow
on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to build on"
        required: false
        type: string
        default: "ubuntu-latest"
      version:
        description: "Version to publish in the form 'major.minor.patch'"
        required: true
        type: string
      python-version:
        description: "Python version to use in the build process"
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ${{ inputs.os }}
    env:
      RELEASE_NOTES_FILE: release_notes.md
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash
      - name: Install scripts dependencies
        run: |
          make install-scripts-reqs
        shell: bash
      - name: Build project
        run: |
          make build-package
        shell: bash
      - name: Extract release notes
        run: |
          python scripts/gh_actions/extract_release_notes.py \
          -f CHANGELOG.md -o $RELEASE_NOTES_FILE -v ${{ inputs.version }}
        shell: bash
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body_path: ${{ env.RELEASE_NOTES_FILE }}
          draft: false
          prerelease: false
